// <auto-generated />
using BlazorCine.Server.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCine.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221210171255_DataBase")]
    partial class DataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorCine.Server.Model.Entities.Cartelera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Horario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sala")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carteleras");
                });

            modelBuilder.Entity("BlazorCine.Server.Model.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarteleraId")
                        .HasColumnType("int");

                    b.Property<int>("Hora")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarteleraId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("BlazorCine.Server.Model.Entities.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarteleraId")
                        .HasColumnType("int");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarteleraId");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("BlazorCine.Server.Model.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarteleraId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioSala")
                        .HasColumnType("int");

                    b.Property<string>("TipoSala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarteleraId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("BlazorCine.Server.Model.Entities.Horario", b =>
                {
                    b.HasOne("BlazorCine.Server.Model.Entities.Cartelera", "Carteleras")
                        .WithMany("Horarios")
                        .HasForeignKey("CarteleraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carteleras");
                });

            modelBuilder.Entity("BlazorCine.Server.Model.Entities.Pelicula", b =>
                {
                    b.HasOne("BlazorCine.Server.Model.Entities.Cartelera", "Carteleras")
                        .WithMany("Peliculas")
                        .HasForeignKey("CarteleraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carteleras");
                });

            modelBuilder.Entity("BlazorCine.Server.Model.Entities.Sala", b =>
                {
                    b.HasOne("BlazorCine.Server.Model.Entities.Cartelera", "Carteleras")
                        .WithMany("Salas")
                        .HasForeignKey("CarteleraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carteleras");
                });

            modelBuilder.Entity("BlazorCine.Server.Model.Entities.Cartelera", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Peliculas");

                    b.Navigation("Salas");
                });
#pragma warning restore 612, 618
        }
    }
}
